### ISSUE TITLE
[Bug]: spotx@1.8-20230927-5074dc - Resource was not found | PS1 was renamed from Install.ps1 to Run.ps1

### ISSUE THREAD

**Issue by PlatFlat** [JourneyOver/scoop-buckets#11]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

spotx

### Expected/Current Behaviour

Spotx (https://github.com/SpotX-Official/SpotX)

Installer PS1 was renamed from Install.ps1 to Run.ps1

spotx [Install.ps1](https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1) (now 404 Not Found) was renamed to [run.ps1](https://github.com/SpotX-Official/SpotX/blob/main/run.ps1)

### Steps to Reproduce

```console
scoop update spotx
ERROR Download failed! (Error 3) Resource was not found
ERROR https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1
    referer=https://raw.githubusercontent.com/amd64fox/SpotX/main/
    dir=C:\Users\Administrator\scoop\cache
    out=spotx#1.8-20230927-5074dc#https_raw.githubusercontent.com_amd64fox_SpotX_main_Install.ps1
```

### Possible Solution

Installer URL should be rename according.
From: https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1
To: https://raw.githubusercontent.com/amd64fox/SpotX/main/run.ps1

### Scoop and Buckets Version

```console
-
```

### Scoop Config

```console
-
```

### PowerShell Version

```console
-
```

**Comment by JourneyOver** [comment]
Thanks for letting me know! Update will be pushed in a second for this..

Honestly surprised anyone is actually using this spotx install as I have it set to only install a specific version of Spotify (version 1.2.13.661.ga588f749-4064 which was before the spotify theme changed for the worse imo)
